Shop/Models/Answer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int answerID { get; set; }
        public string answerText { get; set; }
        public Nullable<System.DateTime> answerDate { get; set; }
        public Nullable<int> questionID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> approveUserID { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}

Shop/Controllers/AnswerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Shop.Models;
using PagedList;

namespace Shop.Controllers
{
    public class AnswerController : Controller
    {
        private Rizkaran_SiteEntities db = new Rizkaran_SiteEntities();

        [RequsetLogin(2)]
        // GET: Answer
        public ActionResult Index(string search,int?page,string sort)
        {
            IEnumerable<Answer>model = db.Answers.Include(a => a.Question).Include(a => a.User);
            if (search != null)
            {
                model = db.Answers.Where(s => s.Question.Product.name.Contains(search)).ToList();
            }
            switch (sort)
            {
                case "answerText":
                    model = model.OrderBy(s => s.answerText);
                    break;
                case "answerText_desc":
                    model = model.OrderByDescending(s => s.answerText);
                    break;
                case "answerDate":
                    model = model.OrderBy(s => s.answerDate);
                    break;
                case "answerDate_desc":
                    model = model.OrderByDescending(s => s.answerDate);
                    break;
                case "questionText":
                    model = model.OrderBy(s => s.Question.questionText);
                    break;
                case "questionText_desc":
                    model = model.OrderByDescending(s => s.Question.questionText);
                    break;
                case "username":
                    model = model.OrderBy(s => s.User.username);
                    break;
                case "username_desc":
                    model = model.OrderByDescending(s => s.User.username);
                    break;
            }
            ViewBag.SortType = sort;
            return View(model.ToList().ToPagedList(page ?? 1,10));
        }
        [RequsetLogin(2)]
        // GET: Answer/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = db.Answers.Find(id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            return View(answer);
        }
        [RequsetLogin(2)]
        // GET: Answer/Create
        public ActionResult Create()
        {
            ViewBag.questionID = new SelectList(db.Questions, "questionID", "questionText");
            ViewBag.userID = new SelectList(db.Users, "userID", "username");
            return View();
        }

        // POST: Answer/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create([Bind(Include = "answerID,answerText,answerDate,questionID,userID")] Answer answer, int? questionID , int? productID)
        {
            User user = (User)Session["UU!#user"];

            if (user != null)
            {

                answer.questionID = questionID;

                answer.answerDate = Convert.ToDateTime(DateTime.Now.ToString("yyyy-MM-dd hh:mm:ss"));
                answer.userID = user.userID;
                db.Answers.Add(answer);
                db.SaveChanges();

                if (productID == null)
                {
                    return RedirectToAction("index", "answer");

                }
                else
                {
                    return RedirectToAction("show", "product", new { message = "نظر با موفقیت ثبت شد", id = productID });

                }
                //if (ModelState.IsValid)
                //{


                //return RedirectToAction("show", "product", new { message = "نظر با موفقیت ثبت شد", id = productID });
                //}

                //ViewBag.questionID = new SelectList(db.Questions, "questionID", "questionText", answer.questionID);
                //ViewBag.userID = new SelectList(db.Users, "userID", "username", answer.userID);
                //return View(answer);
            }
            else
            {
                return RedirectToAction("show", "product", new { message = "برای ثبت نظر لطقا وارد حساب کاربری شوید", id = productID });
            }



        }
        [RequsetLogin(2)]
        // GET: Answer/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = db.Answers.Find(id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            ViewBag.questionID = new SelectList(db.Questions, "questionID", "questionText", answer.questionID);
            ViewBag.userID = new SelectList(db.Users, "userID", "username", answer.userID);
            return View(answer);
        }
        [RequsetLogin(2)]
        // POST: Answer/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "answerID,answerText,answerDate,questionID,userID")] Answer answer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(answer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.questionID = new SelectList(db.Questions, "questionID", "questionText", answer.questionID);
            ViewBag.userID = new SelectList(db.Users, "userID", "username", answer.userID);
            return View(answer);
        }
        [RequsetLogin(2)]
        // GET: Answer/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = db.Answers.Find(id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            return View(answer);
        }
        [RequsetLogin(2)]
        // POST: Answer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Answer answer = db.Answers.Find(id);
            db.Answers.Remove(answer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }




        [RequsetLogin(2)]
        [HttpPost]
        public ActionResult approveAnswer(int answerID, bool approve)
        {
            User user = new User();
            if (Session["UU!#user"] != null)
            {
                user = (User)Session["UU!#user"];
            }


            if (approve && user != null)
            {
                Answer answer = db.Answers.Find(answerID);
                if (answer != null)
                {
                    answer.approveUserID = user.userID;
                    db.Entry(answer).State = EntityState.Modified;
                    db.SaveChanges();


                    return Json(new { success = true , state = true});


                }
                return Json(new { success = false, state = false });
            }
            else if (!approve)
            {
                Answer answer = db.Answers.Find(answerID);
                db.Answers.Remove(answer);
                db.SaveChanges();

                return Json(new { success = true, state = false });

            }

            return Json(new { success = false, state = false });
        }






    }
}

Shop/Views/Answer/Create.cshtml
@model Shop.Models.Answer

@{
    ViewBag.Title = "Create";
  
}

<h2>جدید</h2>


@using (Html.BeginForm()) 
{
    
    <div class="form-horizontal">
        @*<h4>Answer</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("جواب", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.answerText, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.answerText, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.answerDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.answerDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.answerDate, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.Label("سوال", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("questionID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.questionID, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.Label("نام کاربری", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("userID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.userID, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ثبت" class="btn btn-default" />
                |
                @Html.ActionLink("بازگشت به لیست", "Index")
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

Shop/Views/Answer/Delete.cshtml
@model Shop.Models.Answer

@{
    ViewBag.Title = "Delete";
   
}

<h2>حذف</h2>

<h3>آیا مطمئن هستید که می خواهید حذف کنید؟</h3>
<div>
    @*<h4>Answer</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.answerText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.answerText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.answerDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.answerDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Question.questionText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Question.questionText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.username)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="حذف" class="btn btn-default" /> |
            @Html.ActionLink("بازگشت به لیست", "Index")
        </div>
    }
</div>

Shop/Views/Answer/Details.cshtml
@model Shop.Models.Answer

@{
    ViewBag.Title = "Details";
   
}

<h2>مشاهده</h2>

<div>
    @*<h4>Answer</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.answerText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.answerText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.answerDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.answerDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Question.questionText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Question.questionText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.username)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("ویرایش", "Edit", new { id = Model.answerID }) |
    @Html.ActionLink("بازگشت به لیست", "Index")
</p>

Shop/Views/Answer/Edit.cshtml
@model Shop.Models.Answer

@{
    ViewBag.Title = "Edit";
    
}

<h2>ویرایش</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @*<h4>Answer</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.answerID)

        <div class="form-group">
            @Html.LabelFor(model => model.answerText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.answerText, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.answerText, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.answerDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.answerDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.answerDate, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.Label("سوال", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("questionID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.questionID, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.Label("نام کاربری", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("userID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.userID, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ذخیره" class="btn btn-default" />
                |
                @Html.ActionLink("بازگشت به لیست", "Index")
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
    CKEDITOR('#answerText');
    </script>
}

Shop/Views/Answer/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<Shop.Models.Answer>

@{
    ViewBag.Title = "Index";

}

@*<h2>Index</h2>*@
<style>
    input[type=text] {
        width: 250px;
        height: 35px;
        border-radius: 4px;
        outline: none;
        border: 1px solid #DDDDDD;
        padding: 8px;
    }

    input:focus {
        border-color: #16a7eb;
        box-shadow: 0 0 5px rgba(81, 203, 238, 1);
    }
</style>
<p>
    @Html.ActionLink("جدید", "Create")
</p>
<p>
    @using (Html.BeginForm("Index", "Answer", FormMethod.Get))
    {
        <input type="text" name="search" /> <input type="submit" value="جستجو" class="btn-group btn btn-primary" />
    }
</p>
@{ var sort = ViewBag.SortType;}
<table class="table">
    <tr>
        <th>
           
                <a  style="color:white">جواب</a>
                
            
        </th>
        <th>
            @{ if (sort == "answerDate")
                {
                <a href="/Answer/Index/?sort=answerDate_desc" style="color:white"> تاریخ  </a>
                }
               else
                {
                <a href="/Answer/Index/?sort=answerDate" style="color:white">تاریخ </a>
                }
            }
        </th>
        <th>
           
              
                <a style="color:white">سوال</a>
              
        </th>
        <th>
            @{ if (sort == "username")
                {
                <a href="/Answer/Index/?sort=username_desc" style="color:white"> نام کاربری</a>
                } 
               else
                {
                <a href="/Answer/Index/?sort=username" style="color:white">نام کاربری</a>
                }
            }
        </th>
        <th>

        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr id="@item.answerID">
            <td>
                @Html.DisplayFor(modelItem => item.answerText)
            </td>
            <td>
                @if (item.answerDate.HasValue)
                {
                    @pep.pep.toPersianDateString((DateTime)item.answerDate)
                }

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Question.questionText)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.username)
            </td>
            <td>
                @Html.ActionLink("ویرایش", "Edit", new { id = item.answerID }) |
                @Html.ActionLink("مشاهده", "Details", new { id = item.answerID }) |
                @Html.ActionLink("حذف", "Delete", new { id = item.answerID })
            </td>
            <td>
                @{
                    if (item.approveUserID == null)
                    {
                        <a data-id="p-@item.answerID" style="font-size:25px;color:green" onclick="approveAnswer(@item.answerID,true)"><i class="fa fa-check"></i></a>
                        <a data-id="n-@item.answerID" style="font-size:25px;color:red" onclick="approveAnswer(@item.answerID,false)"><i class="fa fa-times"></i></a>


                    }
                }

            </td>
        </tr>
    }

</table>
<div class="panel-body">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }), PagedListRenderOptions.ClassicPlusFirstAndLast)
</div>


<script>

    function approveAnswer(answerID, approve) {

            $.ajax({
                type: "POST",
                url: '@Url.Action("approveAnswer", "answer")',

                data: { answerID: answerID , approve: approve },

                success: function (data) {

                    if (data.state) {
                        $("[data-id=p-" + answerID + "]").css("color", "green");
                        $("[data-id=p-" + answerID + "]").hide(200);
                    }
                    else {
                        $("#" + answerID).hide(200);

                    }

                },
                error: function () { SnakeBar("خطا "); }
            });
        }
</script>