Shop/Models/Orde.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orde
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orde()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
            this.OrderProducts = new HashSet<OrderProduct>();
        }
    
        public int orderID { get; set; }
        public Nullable<decimal> orderOff { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> addressID { get; set; }
        public Nullable<int> orderStateID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<byte> paymentTypeID { get; set; }
        public string description { get; set; }
        public Nullable<int> shippingCost { get; set; }
        public string paymentCode { get; set; }
        public string paymentId { get; set; }
        public Nullable<System.DateTime> paymentDate { get; set; }
    
        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
        public virtual OrderState OrderState { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual User User { get; set; }
    }
}

Shop/Controllers/OrdeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Shop.Models;
using PagedList;
using Stimulsoft.Report.Dictionary;
using pep;
using Stimulsoft.Report.Mvc;

namespace Shop.Controllers
{
    public class OrdeController : Controller
    {
        private Rizkaran_SiteEntities db = new Rizkaran_SiteEntities();
        [RequsetLogin(2)]
        // GET: Orde
        public ActionResult Index(string search, int? page, string sort)
        {
            IEnumerable<Orde> model = db.Ordes.Include(o => o.Address).Include(o => o.OrderState).Include(o => o.User);
            if (search != null)
            {
                model = db.Ordes.Where(s => s.User.name.Contains(search)).ToList();
            }

            try
            {
                switch (sort)
                {
                    case "orderOff":
                        model = model.OrderBy(s => s.orderOff);
                        break;
                    case "orderOff_desc":
                        model = model.OrderByDescending(s => s.orderOff);
                        break;
                    //case "addressDetail":
                    //model = model.OrderBy(s => s.Address.addressDetail);
                    //break;
                    //case "addressDetail_desc":
                    //model = model.OrderByDescending(s => s.Address.addressDetail);
                    //break;
                    //case "state":
                    //    model = model.OrderBy(s => s.OrderState.state);
                    //    break;
                    //case "state_desc":
                    //    model = model.OrderByDescending(s => s.OrderState.state);
                    //    break;
                    case "username":
                        model = model.OrderBy(s => s.User.username);
                        break;
                    case "username_desc":
                        model = model.OrderByDescending(s => s.User.username);
                        break;
                    case "date":
                        model = model.OrderBy(s => s.date);
                        break;
                    case "date_desc":
                        model = model.OrderByDescending(s => s.date);
                        break;
                }
            }
            catch (Exception e)
            {

            }




            ViewBag.SortType = sort;
            return View(model.ToList().ToPagedList(page ?? 1, 10));
        }
        [RequsetLogin(2)]
        // GET: Orde/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Orde orde = db.Ordes.Find(id);
            if (orde == null)
            {
                return HttpNotFound();
            }
            return View(orde);
        }
        [RequsetLogin(2)]
        // GET: Orde/Create
        public ActionResult Create()
        {
            ViewBag.addressID = new SelectList(db.Addresses, "addressID", "addressDetail");
            ViewBag.orderStateID = new SelectList(db.OrderStates, "orderStateID", "state");
            ViewBag.userID = new SelectList(db.Users, "userID", "username");
            return View();
        }
        [RequsetLogin(2)]
        // POST: Orde/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "orderID,orderOff,date,userID,addressID,orderStateID")] Orde orde)
        {
            if (ModelState.IsValid)
            {
                db.Ordes.Add(orde);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.addressID = new SelectList(db.Addresses, "addressID", "addressDetail", orde.addressID);
            ViewBag.orderStateID = new SelectList(db.OrderStates, "orderStateID", "state", orde.orderStateID);
            ViewBag.userID = new SelectList(db.Users, "userID", "username", orde.userID);
            return View(orde);
        }
        [RequsetLogin(2)]
        // GET: Orde/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Orde orde = db.Ordes.Find(id);
            if (orde == null)
            {
                return HttpNotFound();
            }
            ViewBag.addressID = new SelectList(db.Addresses, "addressID", "addressDetail", orde.addressID);
            ViewBag.orderStateID = new SelectList(db.OrderStates, "orderStateID", "state", orde.orderStateID);
            ViewBag.userID = new SelectList(db.Users, "userID", "username", orde.userID);
            return View(orde);
        }
        [RequsetLogin(2)]
        // POST: Orde/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "orderID,orderOff,date,userID,addressID,orderStateID")] Orde orde)
        {
            if (ModelState.IsValid)
            {
                db.Entry(orde).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.addressID = new SelectList(db.Addresses, "addressID", "addressDetail", orde.addressID);
            ViewBag.orderStateID = new SelectList(db.OrderStates, "orderStateID", "state", orde.orderStateID);
            ViewBag.userID = new SelectList(db.Users, "userID", "username", orde.userID);
            return View(orde);
        }
        [RequsetLogin(2)]
        // GET: Orde/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Orde orde = db.Ordes.Find(id);
            if (orde == null)
            {
                return HttpNotFound();
            }
            return View(orde);
        }
        [RequsetLogin(2)]
        // POST: Orde/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Orde orde = db.Ordes.Find(id);
            db.Ordes.Remove(orde);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Shop/Views/Orde/Create.cshtml
@model Shop.Models.Orde

@{
    ViewBag.Title = "Create";
   
}

<h2>جدید</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    @*<h4>Orde</h4>*@
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.orderOff, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.orderOff, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.orderOff, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("نام کاربری", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("userID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.userID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("آدرس", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("addressID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.addressID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("وضعیت", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("orderStateID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.orderStateID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="ثبت" class="btn btn-default" />
            |
            @Html.ActionLink("بازگشت به لیست", "Index")
        </div>
    </div>
</div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Shop/Views/Orde/Delete.cshtml
@model Shop.Models.Orde

@{
    ViewBag.Title = "Delete";
    
}

<h2>حذف</h2>

<h3>آیا مطمئن هستید که می خواهید حذف کنید؟</h3>
<div>
    @*<h4>Orde</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.orderOff)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.orderOff)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address.addressDetail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address.addressDetail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderState.state)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderState.state)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.username)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>


    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="حذف" class="btn btn-default" /> |
            @Html.ActionLink("بازگشت به لیست", "Index")
        </div>
    }
</div>

Shop/Views/Orde/Details.cshtml
@model Shop.Models.Orde

@{
    ViewBag.Title = "Details";
    
}

<h2>مشاهده</h2>

<div>
    @*<h4>Orde</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.orderOff)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.orderOff)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address.addressDetail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address.addressDetail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderState.state)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderState.state)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>


    </dl>
</div>
<p>
    @Html.ActionLink("ویرایش", "Edit", new { id = Model.orderID }) |
    @Html.ActionLink("بازگشت به لیست", "Index")
</p>

Shop/Views/Orde/Edit.cshtml
@model Shop.Models.Orde

@{
    ViewBag.Title = "Edit";
   
}

<h2>ویرایش</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    @*<h4>Orde</h4>*@
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.orderID)

    <div class="form-group">
        @Html.LabelFor(model => model.orderOff, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.orderOff, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.orderOff, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("نام کاربری", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("userID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.userID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("آدرس", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("addressID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.addressID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("وضعیت سفارش", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("orderStateID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.orderStateID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.date ,htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="ذخیره" class="btn btn-default" />
            |
            @Html.ActionLink("بازگشت به لیست", "Index")
        </div>
    </div>
</div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Shop/Views/Orde/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<Shop.Models.Orde>

@{
    ViewBag.Title = "Index";

}

@*<h2>Index</h2>*@

@*<p>
        @Html.ActionLink("جدید", "Create")
    </p>*@
<style>
    input[type=text] {
        width: 250px;
        height: 35px;
        border-radius: 4px;
        outline: none;
        border: 1px solid #DDDDDD;
        padding: 8px;
    }

    input:focus {
        border-color: #16a7eb;
        box-shadow: 0 0 5px rgba(81, 203, 238, 1);
    }
</style>
<p>
    @using (Html.BeginForm("Index", "Orde", FormMethod.Get))
    {
        <input type="text" name="search" /> <input type="submit" value="جستجو" class="btn-group btn btn-primary" />
    }
</p>
@{ var sort = ViewBag.SortType;}
<table class="table">
    <tr>
        <th>
            @{ if (sort == "orderOff")
                {
                    <a href="/Orde/Index/?sort=orderOff_desc" style="color:white"> تخفیف </a>
                }
                else
                {
                    <a href="/Orde/Index/?sort=orderOff" style="color:white">تخفیف</a>
                }
            }
        </th>
        <th>
           
                    <a style="color:white">آدرس</a>
             
        </th>
        <th>
          
                    <a  style="color:white">وضعیت</a>
             

        </th>
        <th>
            @{ if (sort == "username")
                {
                    <a href="/Orde/Index/?sort=username_desc" style="color:white"> نام کاربری </a>
                }
                else
                {
                    <a href="/Orde/Index/?sort=username" style="color:white">نام کاربری</a>
                }
            }
        </th>
        <th>
            @{ if (sort == "date")
                {
                    <a href="/Orde/Index/?sort=date_desc" style="color:white"> تاریخ </a>
                }
                else
                {
                    <a href="/Orde/Index/?sort=date" style="color:white">تاریخ</a>
                }
            }
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.orderOff)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address.addressDetail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderState.state)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.username)
            </td>
            <td>
                @if (item.date != null)
                {
                    @pep.pep.toPersianDateString((DateTime)item.date)
                }

            </td>
            <td>
                @Html.ActionLink("ویرایش", "Edit", new { id = item.orderID }) |
                @Html.ActionLink("مشاهده", "Details", new { id = item.orderID }) |
                @Html.ActionLink("حذف", "Delete", new { id = item.orderID })
            </td>
        </tr>
    }

</table>
<div class="panel-body">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }), PagedListRenderOptions.ClassicPlusFirstAndLast)
</div>